import json

from backend.ai.gemini_client import generate_with_gemini


def generate_career_analysis(
    resume_text: str,
    resume_skills: list,
    career_candidates: list
) -> dict:
    """
    Use Gemini to transform the deterministic
    career recommendations into intelligent,
    personalized career advice.
    """

    prompt = f"""
You are ResumeIQ's Senior Career Intelligence Engine.

Your job is to analyze a candidate's resume and the
career recommendations generated by ResumeIQ's
deterministic career matching engine.

IMPORTANT RULES:

1. Use ONLY information present in the resume.
2. Never invent experience, projects, companies,
   certifications, education or skills.
3. Do not claim the candidate knows a skill unless
   the resume provides evidence.
4. Clearly distinguish existing skills from missing skills.
5. Give realistic advice for an early-career candidate.
6. Prioritize skills that provide the highest career value.
7. Recommend practical projects that can be added to
   the candidate's portfolio.
8. Keep recommendations technically realistic.
9. Do not recommend a skill as already possessed if it
   only appears as a missing skill.
10. Return ONLY valid JSON.
11. Do not use markdown.
12. Do not wrap the JSON in ```json blocks.

RESUME:

{resume_text}


DETECTED RESUME SKILLS:

{json.dumps(resume_skills, indent=2)}


CAREER MATCHING ENGINE RESULTS:

{json.dumps(career_candidates, indent=2)}


Return JSON using EXACTLY this structure:

{{
    "recommended_career": {{
        "title": "string",
        "reason": "string",
        "fit_score": 0
    }},

    "career_summary": "string",

    "current_strengths": [
        "string"
    ],

    "missing_skills": [
        "string"
    ],

    "recommended_skills": [
        {{
            "skill": "string",
            "reason": "string",
            "priority": "High"
        }}
    ],

    "recommended_projects": [
        {{
            "title": "string",
            "description": "string",
            "skills": [
                "string"
            ]
        }}
    ],

    "roadmap": {{
        "days_30": [
            "string"
        ],
        "days_60": [
            "string"
        ],
        "days_90": [
            "string"
        ]
    }},

    "final_advice": "string"
}}
"""

    response = generate_with_gemini(prompt)

    # ----------------------------------------------------
    # Parse Gemini JSON
    # ----------------------------------------------------

    try:

        cleaned = response.strip()

        # Remove accidental markdown fences
        if cleaned.startswith("```"):
            cleaned = cleaned.replace(
                "```json",
                "",
                1
            )

            cleaned = cleaned.replace(
                "```",
                "",
                1
            )

            cleaned = cleaned.strip()

        result = json.loads(cleaned)

        if not isinstance(result, dict):
            raise ValueError(
                "Gemini response is not a JSON object."
            )

        return result

    except Exception as e:

        raise RuntimeError(
            "Gemini returned an invalid career analysis."
        ) from e